/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AnimalCreate } from './models/AnimalCreate';
export type { AnimalRead } from './models/AnimalRead';
export type { AnimalResponse } from './models/AnimalResponse';
export type { AnimalUpdate } from './models/AnimalUpdate';
export type { AnswerCreateBulkResponse } from './models/AnswerCreateBulkResponse';
export type { AnswerCreateFailed } from './models/AnswerCreateFailed';
export type { AnswerRead } from './models/AnswerRead';
export type { AnswerRecordCreate } from './models/AnswerRecordCreate';
export type { AnswerRecordId } from './models/AnswerRecordId';
export type { AnswerRecordResponse } from './models/AnswerRecordResponse';
export type { AnswerResponse } from './models/AnswerResponse';
export type { AnswerSummary } from './models/AnswerSummary';
export type { AnswerUpdate } from './models/AnswerUpdate';
export type { AnswerUpdateBulkResponse } from './models/AnswerUpdateBulkResponse';
export type { AnswerUpdateFailed } from './models/AnswerUpdateFailed';
export type { Body_Question_create_question } from './models/Body_Question_create_question';
export type { Body_Question_create_questions } from './models/Body_Question_create_questions';
export type { Body_Question_update_questions } from './models/Body_Question_update_questions';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { QuestionCreateBulkResponse } from './models/QuestionCreateBulkResponse';
export type { QuestionCreateFailedResponse } from './models/QuestionCreateFailedResponse';
export type { QuestionDeleteBulkResponse } from './models/QuestionDeleteBulkResponse';
export type { QuestionId } from './models/QuestionId';
export type { QuestionResponse } from './models/QuestionResponse';
export type { QuestionSetCreateBody } from './models/QuestionSetCreateBody';
export type { QuestionSetRead } from './models/QuestionSetRead';
export type { QuestionSetRequest } from './models/QuestionSetRequest';
export type { QuestionSetResponse } from './models/QuestionSetResponse';
export type { QuestionUpdateBulkResponse } from './models/QuestionUpdateBulkResponse';
export type { QuestionUpdateFailedResponse } from './models/QuestionUpdateFailedResponse';
export type { QuestionWithListAnswer } from './models/QuestionWithListAnswer';
export type { QuestionWithListAnswerCreateResponse } from './models/QuestionWithListAnswerCreateResponse';
export type { QuestionWithListAnswerDeleteResponse } from './models/QuestionWithListAnswerDeleteResponse';
export type { QuestionWithListAnswerUpdate } from './models/QuestionWithListAnswerUpdate';
export type { QuestionWithListAnswerUpdateResponse } from './models/QuestionWithListAnswerUpdateResponse';
export type { SymptomCreateBody } from './models/SymptomCreateBody';
export type { SymptomRead } from './models/SymptomRead';
export type { SymptomResponse } from './models/SymptomResponse';
export type { SymptomSummary } from './models/SymptomSummary';
export type { SymptomUpdate } from './models/SymptomUpdate';
export type { SymptomWithQuestions } from './models/SymptomWithQuestions';
export type { TicketAnswer } from './models/TicketAnswer';
export type { TicketAnswerRead } from './models/TicketAnswerRead';
export type { TicketCreate } from './models/TicketCreate';
export type { TicketDataResponse } from './models/TicketDataResponse';
export type { TicketEachSummaryResponse } from './models/TicketEachSummaryResponse';
export type { TicketId } from './models/TicketId';
export type { TicketInfo } from './models/TicketInfo';
export type { TicketLabel } from './models/TicketLabel';
export type { TicketQuestionRead } from './models/TicketQuestionRead';
export type { TicketSummaryResponse } from './models/TicketSummaryResponse';
export type { UrgencyMostRequest } from './models/UrgencyMostRequest';
export type { UrgencyRead } from './models/UrgencyRead';
export type { UrgencyResponse } from './models/UrgencyResponse';
export type { UrgentCaseCreate } from './models/UrgentCaseCreate';
export type { UrgentCaseResponse } from './models/UrgentCaseResponse';
export type { UrgentCaseUpdate } from './models/UrgentCaseUpdate';
export type { UrgentCaseWithUrgency } from './models/UrgentCaseWithUrgency';
export type { ValidationError } from './models/ValidationError';

export { AnimalsService } from './services/AnimalsService';
export { AnswerRecordsService } from './services/AnswerRecordsService';
export { DefaultService } from './services/DefaultService';
export { QuestionService } from './services/QuestionService';
export { QuestionSetService } from './services/QuestionSetService';
export { SummaryService } from './services/SummaryService';
export { SymptomsService } from './services/SymptomsService';
export { TicketQuestionsService } from './services/TicketQuestionsService';
export { TicketsService } from './services/TicketsService';
export { UrgencyService } from './services/UrgencyService';
export { UrgentCasesService } from './services/UrgentCasesService';
